version: '3.4'

services:
  app:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
